apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc-restorefromsnap
spec:
  storageClassName: csi-xtremio-sc
  dataSource:
    name: sql-gold-newsnap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

