apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment-from-snap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssqldeploy1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssqldeploy1
        image: dellregistry.com:5000/mssql/rhel/server:2019-CTP3.0 
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Enterprise"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql-pvc-restorefromsnap

